name: Build Mold Forge Mac Intel

on:
  workflow_dispatch:

jobs:
  build_intel:
    name: Build on macOS Intel (Old Rules)
    runs-on: macos-14

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      shell: bash
      run: |
        pip install cadquery
        pip install -r requirements.txt
        pip install PySide6==6.6.3 pyinstaller

    - name: Build with PyInstaller
      shell: bash
      run: |
        pyinstaller MoldForge_m86.spec

    - name: Codesign ad-hoc
      run: codesign --force --deep --sign - dist/MOLDFORGE_RELEASE/MoldForge.app

    - name: Package for Intel Release
      run: |
        cd dist/MOLDFORGE_RELEASE
        zip -ry ../../MoldForge-macOS-Intel_x64.zip .

    - name: Upload Intel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoldForge-Mac-Intel
        path: MoldForge-macOS-Intel_x64.zip