name: Build Mac (Self-Hosted Intel/Rosetta)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: [self-hosted, mac-local]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Virtual Environment, Install and Build (x86_64)
      run: |
        arch -x86_64 python3 -m venv venv
        source venv/bin/activate
        
        arch -x86_64 python3 -m pip install --upgrade pip
        arch -x86_64 python3 -m pip install -r requirements.txt
        arch -x86_64 python3 -m pip install pyinstaller
        
        arch -x86_64 python3 -m PyInstaller --noconfirm MoldForge_mac.spec
    
    - name: Ad-hoc Codesign for x86_64
      run: |
        find dist/MOLDFORGE_RELEASE -type f \( -name "*.dylib" -o -name "*.so" \) -exec codesign --force --sign - {} \;
        
        codesign --force --sign - dist/MOLDFORGE_RELEASE/MoldForge

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoldForge-Mac
        path: dist/